baseurl = "https://canertuzunar.github.io"
title = "Caner Tuzunar"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "Caner Tuzunar"
  faviconfile = "images/favicon.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan", "javascript", "golang", "rust"]
  uselatex = true
  progressively = false
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/canertuzunar"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/tuzunar"
    weight = 4
#[[menu.primary]]
#    name = "Subscribe"
#    url = "/index.xml"
#    weight = 5